export const BASE_ERROR_CODES_FR = {
  USER_NOT_FOUND: "Utilisateur non trouvé",
  FAILED_TO_CREATE_USER: "Échec de la création de l'utilisateur",
  FAILED_TO_CREATE_SESSION: "Échec de la création de la session",
  FAILED_TO_UPDATE_USER: "Échec de la mise à jour de l'utilisateur",
  FAILED_TO_GET_SESSION: "Échec de la récupération de la session",
  INVALID_PASSWORD: "Mot de passe invalide",
  INVALID_EMAIL: "E-mail invalide",
  INVALID_EMAIL_OR_PASSWORD: "E-mail ou mot de passe invalide",
  INVALID_USER: "Utilisateur invalide",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "Compte social déjà associé",
  PROVIDER_NOT_FOUND: "Fournisseur non trouvé",
  INVALID_TOKEN: "Jeton invalide",
  TOKEN_EXPIRED: "Jeton expiré",
  ID_TOKEN_NOT_SUPPORTED: "id_token non pris en charge",
  FAILED_TO_GET_USER_INFO: "Échec de la récupération des informations utilisateur",
  USER_EMAIL_NOT_FOUND: "E-mail utilisateur non trouvé",
  EMAIL_NOT_VERIFIED: "E-mail non vérifié",
  PASSWORD_TOO_SHORT: "Mot de passe trop court",
  PASSWORD_TOO_LONG: "Mot de passe trop long",
  USER_ALREADY_EXISTS: "L'utilisateur existe déjà.",
  USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL: "L'utilisateur existe déjà. Veuillez utiliser une autre adresse e-mail.",
  EMAIL_CAN_NOT_BE_UPDATED: "L'adresse e-mail ne peut pas être mise à jour",
  CREDENTIAL_ACCOUNT_NOT_FOUND: "Compte d'authentification non trouvé",
  SESSION_EXPIRED: "Session expirée. Veuillez vous reconnecter pour effectuer cette action.",
  FAILED_TO_UNLINK_LAST_ACCOUNT: "Vous ne pouvez pas délier votre dernier compte",
  ACCOUNT_NOT_FOUND: "Compte non trouvé",
  USER_ALREADY_HAS_PASSWORD: "L'utilisateur possède déjà un mot de passe. Fournissez-le pour supprimer le compte.",
  CROSS_SITE_NAVIGATION_LOGIN_BLOCKED: "Connexion par navigation intersite bloquée. Cette requête semble être une attaque CSRF.",
  VERIFICATION_EMAIL_NOT_ENABLED: "L'e-mail de vérification n'est pas activé",
  EMAIL_ALREADY_VERIFIED: "L'e-mail est déjà vérifié",
  EMAIL_MISMATCH: "Les adresses e-mail ne correspondent pas",
  SESSION_NOT_FRESH: "La session n'est pas récente",
  LINKED_ACCOUNT_ALREADY_EXISTS: "Le compte lié existe déjà",
  INVALID_ORIGIN: "Origine invalide",
  INVALID_CALLBACK_URL: "callbackURL invalide",
  INVALID_REDIRECT_URL: "redirectURL invalide",
  INVALID_ERROR_CALLBACK_URL: "errorCallbackURL invalide",
  INVALID_NEW_USER_CALLBACK_URL: "newUserCallbackURL invalide",
  MISSING_OR_NULL_ORIGIN: "Origine manquante ou nulle",
  CALLBACK_URL_REQUIRED: "callbackURL est requis",
  FAILED_TO_CREATE_VERIFICATION: "Impossible de créer la vérification",
  FIELD_NOT_ALLOWED: "Champ non autorisé",
  ASYNC_VALIDATION_NOT_SUPPORTED: "La validation asynchrone n'est pas prise en charge",
  VALIDATION_ERROR: "Erreur de validation",
  MISSING_FIELD: "Ce champ est obligatoire",
  METHOD_NOT_ALLOWED_DEFER_SESSION_REQUIRED: "La méthode POST nécessite l'activation de deferSessionRefresh dans la configuration de la session",
  BODY_MUST_BE_AN_OBJECT: "Le corps de la requête doit être un objet",
  PASSWORD_ALREADY_SET: "L'utilisateur a déjà un mot de passe configuré"
} as const;

const BASE_ERROR_CODES_EN = {
  USER_NOT_FOUND: "User not found",
  FAILED_TO_CREATE_USER: "Failed to create user",
  FAILED_TO_CREATE_SESSION: "Failed to create session",
  FAILED_TO_UPDATE_USER: "Failed to update user",
  FAILED_TO_GET_SESSION: "Failed to get session",
  INVALID_PASSWORD: "Invalid password",
  INVALID_EMAIL: "Invalid email",
  INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
  INVALID_USER: "Invalid user",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "Social account already linked",
  PROVIDER_NOT_FOUND: "Provider not found",
  INVALID_TOKEN: "Invalid token",
  TOKEN_EXPIRED: "Token expired",
  ID_TOKEN_NOT_SUPPORTED: "id_token not supported",
  FAILED_TO_GET_USER_INFO: "Failed to get user info",
  USER_EMAIL_NOT_FOUND: "User email not found",
  EMAIL_NOT_VERIFIED: "Email not verified",
  PASSWORD_TOO_SHORT: "Password too short",
  PASSWORD_TOO_LONG: "Password too long",
  USER_ALREADY_EXISTS: "User already exists.",
  USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL: "User already exists. Use another email.",
  EMAIL_CAN_NOT_BE_UPDATED: "Email can not be updated",
  CREDENTIAL_ACCOUNT_NOT_FOUND: "Credential account not found",
  SESSION_EXPIRED: "Session expired. Re-authenticate to perform this action.",
  FAILED_TO_UNLINK_LAST_ACCOUNT: "You can't unlink your last account",
  ACCOUNT_NOT_FOUND: "Account not found",
  USER_ALREADY_HAS_PASSWORD: "User already has a password. Provide that to delete the account.",
  CROSS_SITE_NAVIGATION_LOGIN_BLOCKED: "Cross-site navigation login blocked. This request appears to be a CSRF attack.",
  VERIFICATION_EMAIL_NOT_ENABLED: "Verification email isn't enabled",
  EMAIL_ALREADY_VERIFIED: "Email is already verified",
  EMAIL_MISMATCH: "Email mismatch",
  SESSION_NOT_FRESH: "Session is not fresh",
  LINKED_ACCOUNT_ALREADY_EXISTS: "Linked account already exists",
  INVALID_ORIGIN: "Invalid origin",
  INVALID_CALLBACK_URL: "Invalid callbackURL",
  INVALID_REDIRECT_URL: "Invalid redirectURL",
  INVALID_ERROR_CALLBACK_URL: "Invalid errorCallbackURL",
  INVALID_NEW_USER_CALLBACK_URL: "Invalid newUserCallbackURL",
  MISSING_OR_NULL_ORIGIN: "Missing or null Origin",
  CALLBACK_URL_REQUIRED: "callbackURL is required",
  FAILED_TO_CREATE_VERIFICATION: "Unable to create verification",
  FIELD_NOT_ALLOWED: "Field not allowed to be set",
  ASYNC_VALIDATION_NOT_SUPPORTED: "Async validation is not supported",
  VALIDATION_ERROR: "Validation Error",
  MISSING_FIELD: "Field is required",
  METHOD_NOT_ALLOWED_DEFER_SESSION_REQUIRED: "POST method requires deferSessionRefresh to be enabled in session config",
  BODY_MUST_BE_AN_OBJECT: "Body must be an object",
  PASSWORD_ALREADY_SET: "User already has a password set",

	OTP_NOT_ENABLED: "OTP not enabled",
	OTP_HAS_EXPIRED: "OTP has expired",
	TOTP_NOT_ENABLED: "TOTP not enabled",
	TWO_FACTOR_NOT_ENABLED: "Two factor isn't enabled",
	BACKUP_CODES_NOT_ENABLED: "Backup codes aren't enabled",
	INVALID_BACKUP_CODE: "Invalid backup code",
	INVALID_CODE: "Invalid code",
	TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: "Too many attempts. Please request a new code.",
	INVALID_TWO_FACTOR_COOKIE: "Invalid two factor cookie"
} as const;